Repository nole23/UKS-2024, pull requests merged in 2024-12, with the labels that each got.

#24 Create diagram. Closed #1
  diagram/UKS Projekat.pdf
  diagram/classDiagram.png
Labels: documentation

#25 Feature/us #6
  .github/workflows/build-deploy.yml
  client/package-lock.json
  client/src/app/app.component.spec.ts
  client/src/app/auth/auth.component.spec.ts
  client/src/app/auth/auth.guard.spec.ts
  client/src/app/auth/common/header/header.component.spec.ts
  client/src/app/auth/login/login.component.spec.ts
  client/src/app/common/footer/footer.component.spec.ts
  docker-compose.yml
  nginx/Dockerfile
  server/.env.test
  server/requirements.txt
  server/uks/settings.py
  version.txt
Labels: userstory

#34 Feature/us #6
  .github/workflows/build-deploy.yml
  .github/workflows/deploy-docker.yml
Labels: bug, userstory

#37 Update deploy-docker.yml
  .github/workflows/deploy-docker.yml
Labels: bug
